### ISSUE TITLE
can't get it work

### ISSUE THREAD

**Issue by mojitocloud** [marketsentiment/mslive_public#1]
hooked up twitter keys and ran twitter_stream.py it runs but won't output anything

when I run dev_server.py and access it I get

Select...
Live Market Sentiment
Long Term Market Sentiment
🛑 Errors (8)
×
⛑️
Callback error updating live-graph.figure
10:32:17 AM
⛑️
Callback error updating live-graph.figure
10:32:16 AM
⛑️
Callback error updating live-graph.figure
10:32:15 AM
⛑️
Callback error updating live-graph.figure
10:32:14 AM
⛑️
Callback error updating live-graph.figure
10:32:13 AM

**Comment by doylej35** [comment]
Because the code uses Event in dash - which is not not used in the latest version - you need to install dash 0.30.0 and dash-core-components 0.38.0.

**Comment by marketsentiment** [comment]
Yeah. Please use the correct version of dash as @doylej35 suggested!
